"""User profile model for the AI Endurance Coach."""

from typing import Optional

from pydantic import BaseModel


DISCLAIMER = (
    "⚠️ Disclaimer: This analysis is generated by an AI and is for informational "
    "purposes only. It is NOT medical advice. Always consult a qualified coach or "
    "healthcare professional before making changes to your training."
)


class UserProfile(BaseModel):
    """Athlete profile collected via the UI questionnaire."""

    age: Optional[int] = None
    goal: str = ""
    experience: str = ""
    injuries: str = ""
    notes: str = ""

    def to_context(self) -> str:
        """Return a human-readable string for use in LLM prompts.

        Returns:
            Formatted string describing the athlete's profile.
        """
        parts = []
        if self.age:
            parts.append(f"Age: {self.age}")
        if self.goal:
            parts.append(f"Goal: {self.goal}")
        if self.experience:
            parts.append(f"Experience level: {self.experience}")
        if self.injuries:
            parts.append(f"Injuries / limitations: {self.injuries}")
        if self.notes:
            parts.append(f"Additional notes: {self.notes}")

        if not parts:
            return "No athlete profile provided."
        return "\n".join(parts)
